/**
 * Emoji index for mapping emoji names to Unicode characters and vice versa
 *
 * This is a simplified version. For a complete list, see:
 * https://github.com/Tyrrrz/DiscordChatExporter/issues/599#issuecomment-863431045
 */

// Map from emoji character to name
const emojiToCode: Record<string, string> = {
  '😀': 'grinning',
  '😃': 'smiley',
  '😄': 'smile',
  '😁': 'grin',
  '😆': 'laughing',
  '😅': 'sweat_smile',
  '😂': 'joy',
  '🤣': 'rofl',
  '☺️': 'relaxed',
  '😊': 'blush',
  '😇': 'innocent',
  '🙂': 'slight_smile',
  '🙃': 'upside_down',
  '😉': 'wink',
  '😌': 'relieved',
  '😍': 'heart_eyes',
  '🥰': 'smiling_face_with_3_hearts',
  '😘': 'kissing_heart',
  '😗': 'kissing',
  '😙': 'kissing_smiling_eyes',
  '😚': 'kissing_closed_eyes',
  '😋': 'yum',
  '😛': 'stuck_out_tongue',
  '😝': 'stuck_out_tongue_closed_eyes',
  '😜': 'stuck_out_tongue_winking_eye',
  '🤪': 'zany_face',
  '🤨': 'face_with_raised_eyebrow',
  '🧐': 'face_with_monocle',
  '🤓': 'nerd',
  '😎': 'sunglasses',
  '🤩': 'star_struck',
  '🥳': 'partying_face',
  '😏': 'smirk',
  '😒': 'unamused',
  '😞': 'disappointed',
  '😔': 'pensive',
  '😟': 'worried',
  '😕': 'confused',
  '🙁': 'slight_frown',
  '☹️': 'frowning2',
  '😣': 'persevere',
  '😖': 'confounded',
  '😫': 'tired_face',
  '😩': 'weary',
  '🥺': 'pleading_face',
  '😢': 'cry',
  '😭': 'sob',
  '😤': 'triumph',
  '😠': 'angry',
  '😡': 'rage',
  '🤬': 'face_with_symbols_over_mouth',
  '🤯': 'exploding_head',
  '😳': 'flushed',
  '😱': 'scream',
  '😨': 'fearful',
  '😰': 'cold_sweat',
  '😥': 'disappointed_relieved',
  '😓': 'sweat',
  '🤗': 'hugging',
  '🤔': 'thinking',
  '🤭': 'face_with_hand_over_mouth',
  '🤫': 'shushing_face',
  '🤥': 'lying_face',
  '😶': 'no_mouth',
  '😐': 'neutral_face',
  '😑': 'expressionless',
  '😬': 'grimacing',
  '🙄': 'rolling_eyes',
  '😯': 'hushed',
  '😦': 'frowning',
  '😧': 'anguished',
  '😮': 'open_mouth',
  '😲': 'astonished',
  '😴': 'sleeping',
  '🤤': 'drooling_face',
  '😪': 'sleepy',
  '😵': 'dizzy_face',
  '🤐': 'zipper_mouth',
  '🥴': 'woozy_face',
  '🤢': 'nauseated_face',
  '🤮': 'face_vomiting',
  '🤧': 'sneezing_face',
  '😷': 'mask',
  '🤒': 'thermometer_face',
  '🤕': 'head_bandage',
  '🤑': 'money_mouth',
  '🤠': 'cowboy',
  '😈': 'smiling_imp',
  '👿': 'imp',
  '👹': 'japanese_ogre',
  '👺': 'japanese_goblin',
  '🤡': 'clown',
  '💩': 'poop',
  '👻': 'ghost',
  '💀': 'skull',
  '☠️': 'skull_crossbones',
  '👽': 'alien',
  '👾': 'space_invader',
  '🤖': 'robot',
  '🎃': 'jack_o_lantern',
  '😺': 'smiley_cat',
  '😸': 'smile_cat',
  '😹': 'joy_cat',
  '😻': 'heart_eyes_cat',
  '😼': 'smirk_cat',
  '😽': 'kissing_cat',
  '🙀': 'scream_cat',
  '😿': 'crying_cat_face',
  '😾': 'pouting_cat',
  '❤️': 'heart',
  '🧡': 'orange_heart',
  '💛': 'yellow_heart',
  '💚': 'green_heart',
  '💙': 'blue_heart',
  '💜': 'purple_heart',
  '🖤': 'black_heart',
  '🤍': 'white_heart',
  '🤎': 'brown_heart',
  '💔': 'broken_heart',
  '💕': 'two_hearts',
  '💞': 'revolving_hearts',
  '💓': 'heartbeat',
  '💗': 'heartpulse',
  '💖': 'sparkling_heart',
  '💘': 'cupid',
  '💝': 'gift_heart',
  '👍': 'thumbsup',
  '👎': 'thumbsdown',
  '✊': 'fist',
  '👊': 'punch',
  '🤛': 'left_facing_fist',
  '🤜': 'right_facing_fist',
  '👏': 'clap',
  '🙌': 'raised_hands',
  '👐': 'open_hands',
  '🤲': 'palms_up_together',
  '🤝': 'handshake',
  '🙏': 'pray',
  '✍️': 'writing_hand',
  '💅': 'nail_care',
  '🤳': 'selfie',
  '💪': 'muscle',
  '✨': 'sparkles',
  '🔥': 'fire',
  '💯': '100',
  '⭐': 'star',
  '🌟': 'star2',
  '✅': 'white_check_mark',
  '❌': 'x',
  '⚠️': 'warning',
  '❗': 'exclamation',
  '❓': 'question',
  '💤': 'zzz',
  '💬': 'speech_balloon',
  '👀': 'eyes',
  '👁️': 'eye',
  '👂': 'ear',
  '👃': 'nose',
  '👅': 'tongue',
  '👄': 'lips',
  '🧠': 'brain',
};

// Build reverse map from name to emoji
const codeToEmoji: Record<string, string> = {};
for (const [emoji, name] of Object.entries(emojiToCode)) {
  codeToEmoji[name] = emoji;
}

/**
 * Emoji index interface
 */
export const emojiIndex = {
  /**
   * Get emoji name from character
   */
  getCode(emoji: string): string | null {
    return emojiToCode[emoji] ?? null;
  },

  /**
   * Get emoji character from name
   */
  getByName(name: string): string | null {
    return codeToEmoji[name] ?? null;
  },
};
